//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyclinic_Rybakov.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Applicationsss
    {
        public Applicationsss()
        {
            this.Business = new HashSet<Business>();
            this.Conclusion = new HashSet<Conclusion>();
        }
    
        public int Id_application { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public string Status { get; set; }
        public Nullable<int> Id_service { get; set; }
        public Nullable<int> Id_doctor { get; set; }
        public Nullable<int> Id_cabinet { get; set; }
        public Nullable<int> Id_user { get; set; }
    
        public virtual Cabinet Cabinet { get; set; }
        public virtual Doctor Doctor { get; set; }
        public virtual Service Service { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Business> Business { get; set; }
        public virtual ICollection<Conclusion> Conclusion { get; set; }
    }
}
