//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyclinic_Rybakov.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Business
    {
        public int Id_business { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> Id_user { get; set; }
        public Nullable<int> Id_application { get; set; }
        public Nullable<int> Id_conclusion { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual Conclusion Conclusion { get; set; }
        public virtual User User { get; set; }
    }
}
