//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyclinic_Rybakov.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cabinet
    {
        public Cabinet()
        {
            this.Application = new HashSet<Application>();
            this.Service = new HashSet<Service>();
        }
    
        public int Id_cabinet { get; set; }
        public Nullable<int> Id_department { get; set; }
    
        public virtual ICollection<Application> Application { get; set; }
        public virtual Department Department { get; set; }
        public virtual ICollection<Service> Service { get; set; }
    }
}
