//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyclinic_Rybakov.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conclusion
    {
        public Conclusion()
        {
            this.Business = new HashSet<Business>();
        }
    
        public int Id_conclusion { get; set; }
        public string Description { get; set; }
        public Nullable<int> Id_application { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual ICollection<Business> Business { get; set; }
    }
}
