//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyclinic_Rybakov.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public Department()
        {
            this.Cabinet = new HashSet<Cabinet>();
            this.Employees = new HashSet<Employees>();
        }
    
        public int Id_department { get; set; }
        public string Name { get; set; }
        public Nullable<int> Id_polyclinic { get; set; }
    
        public virtual ICollection<Cabinet> Cabinet { get; set; }
        public virtual Polyclinic Polyclinic { get; set; }
        public virtual ICollection<Employees> Employees { get; set; }
    }
}
