//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyclinic_Rybakov.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoctorType
    {
        public DoctorType()
        {
            this.Doctor = new HashSet<Doctor>();
            this.Employees = new HashSet<Employees>();
        }
    
        public int Id_doctorType { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Doctor> Doctor { get; set; }
        public virtual ICollection<Employees> Employees { get; set; }
    }
}
