//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyclinic_Rybakov.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        public int Id_employees { get; set; }
        public string FullName { get; set; }
        public Nullable<int> Id_department { get; set; }
        public Nullable<int> Id_doctorType { get; set; }
        public Nullable<int> Id_Role { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual DoctorType DoctorType { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
