//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyclinic_Rybakov.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PolyclinicEntities : DbContext
    {
        public PolyclinicEntities()
            : base("name=PolyclinicEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Application> Application { get; set; }
        public DbSet<Business> Business { get; set; }
        public DbSet<Cabinet> Cabinet { get; set; }
        public DbSet<Conclusion> Conclusion { get; set; }
        public DbSet<Department> Department { get; set; }
        public DbSet<Doctor> Doctor { get; set; }
        public DbSet<DoctorType> DoctorType { get; set; }
        public DbSet<Employees> Employees { get; set; }
        public DbSet<Polyclinic> Polyclinic { get; set; }
        public DbSet<Roles> Roles { get; set; }
        public DbSet<Service> Service { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<User> User { get; set; }
    }
}
