//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyclinic_Rybakov.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public Service()
        {
            this.Application = new HashSet<Application>();
        }
    
        public int Id_service { get; set; }
        public string Name { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
        public Nullable<int> Id_cabinet { get; set; }
        public Nullable<int> Id_doctor { get; set; }
    
        public virtual ICollection<Application> Application { get; set; }
        public virtual Cabinet Cabinet { get; set; }
        public virtual Doctor Doctor { get; set; }
    }
}
